sudo: required

services:
  - docker
env:
  - DOCKER_REPO=kota661/ibmcloud-sdk
install:
  - echo "docker build"
  - docker build -t $DOCKER_REPO:$TRAVIS_BRANCH .

script:
  - >-
    docker run $DOCKER_REPO:$TRAVIS_BRANCH ibmcloud --version \
    && ibmcloud plugin list | grep -e kubernetes-service -e container-registry \
    && git --version \
    && docker --version \
    && kubectl version --client \
    && helm version --client

after_success:
  - echo "Current branch is ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag $DOCKER_REPO:$TRAVIS_BRANCH $DOCKER_REPO:latest;
      docker push $DOCKER_REPO:latest;
    fi
